name: .NET 5/6 transition progress monitor
on: 
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  generate_image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'
    - run: pip install pycairo==1.20.1 click==8.0.3

    - name: Generate image
      run: python .github/generate_net56_progress_image.py

    - name: Set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACTIONS_S3_PUBLISHER_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACTIONS_S3_PUBLISHER_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Upload to S3
      run: aws s3 cp net56_progress.png s3://fpelletier-test/net56_progress.png --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers --cache-control 'no-cache'
